### ISSUE TITLE
连接上来后报错 Conv inconsistency是什么原因呢

### ISSUE THREAD

**Issue by wushd** [l42111996/java-Kcp#7]
有连接进来disruptorExecutorPool1/10.0.0.7:55938
java.io.IOException: Conv inconsistency
	at kcp.Ukcp.input(Ukcp.java:163)
	at kcp.Ukcp.input(Ukcp.java:149)
	at kcp.RecieveTask.execute(RecieveTask.java:62)
	at threadPool.thread.DistriptorHandler.execute(DistriptorHandler.java:17)
	at threadPool.thread.DistriptorEventHandler.onEvent(DistriptorEventHandler.java:10)
	at threadPool.thread.DistriptorEventHandler.onEvent(DistriptorEventHandler.java:5)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.lang.Thread.run(Thread.java:748)

**Comment by l42111996** [comment]
把参数贴上来看看，conv可以当做客户端与服务器的唯一标识，
useConvChannel参数设置是否使用conv当做唯一标识，如果为false的不需要设置conv的值，
当useConvChannel为false，conv字段客户端与服务器不匹配的时候会出现这个错误，
